algoritmo "semnome"
// Função :
// Autor :
// Data : 25/09/2023
// Seção de Declarações 
var

   contador: inteiro
   resp: inteiro
   numero: inteiro

inicio

      escreval("Informe um número")
      leia(numero)
      
      escreval()
      
      resp <- numero
      
      enquanto (resp >= 0) faca
               
               escreval(resp)
               
               resp <- resp - 1

      fimenquanto

fimalgoritmo
