algoritmo "semnome"
// Função :
// Autor :
// Data : 25/09/2023
// Seção de Declarações 
var

   contador,tempo: inteiro

inicio

      contador <- 0
      
      enquanto (contador <= 59)faca

               escreval(contador)
               
               contador <- contador + 1

               tempo <- 0

               enquanto (tempo <= 1000)faca

                        tempo <- tempo + 1

               fimenquanto

      fimenquanto

fimalgoritmo
